### ISSUE TITLE
Cannot switch between music and vocal.

### ISSUE THREAD

**Issue by wongcheehong** [xuancong84/pikaraoke#1]
As you can see in the screenshot below, for some reason the button is disabled and cannot be switched.
![image](https://user-images.githubusercontent.com/11075969/157450290-14f5fa9c-5d07-463b-9618-8c49ec5245ce.png)
![image](https://user-images.githubusercontent.com/11075969/157450345-5b497709-0bc1-41d5-b1e9-c34b368666e5.png)

**Comment by xuancong84** [comment]
When "Music" and "Voice" are greyed out, the nonvocal and vocal m4a audio file are not ready yet. You need to check whether the vocal splitter backend is running or not, it is in the Info tab. **You must manually create `vocal` and `nonvocal` sub-folder inside your song download path in order to enable vocal splitter.** Vocal/nonvocal m4a audio files once generated, will persist, the next time you play the song, you should be able to switch to vocal/nonvocal.
![image](https://user-images.githubusercontent.com/10172392/157614045-271c91e0-85b4-4178-a3a4-1b505968711a.png)

Vocal splitter runs very slowly when CUDA acceleration is not available (only NVIDIA GPU supports CUDA acceleration), thus, you need to have a decent gaming laptop with a good NVIDIA GPU if you want it to be fast. You also need to install PyTorch properly, `pip install torch` is not enough. See the command line on PyTorch official website, run this in Anaconda3's powershell:
![image](https://user-images.githubusercontent.com/10172392/157614541-89f2a9df-6df0-4187-bbb9-186af519a9cc.png)

In the backend, you should see something like this when splitting vocal sounds (without CUDA acceleration, a 5-minute song takes about 2.5 minutes for vocal splitting):
![image](https://user-images.githubusercontent.com/10172392/157615096-07cc334f-0004-406b-a8cc-59802300b354.png)

**Comment by wongcheehong** [comment]
Fixed with manually create vocal and nonvocal folder. Also noted that pytorch from requirement.txt doesn't have cuda support, need to follow pytorch official install guide.
